// <auto-generated />
using DroppboxApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DroppboxApi.Migrations
{
    [DbContext(typeof(DroppboxContext))]
    partial class DroppboxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DroppboxApi.Models.File", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("folderId");

                    b.Property<string>("name");

                    b.Property<string>("path");

                    b.Property<int>("size");

                    b.Property<string>("typ");

                    b.HasKey("id");

                    b.ToTable("files");
                });

            modelBuilder.Entity("DroppboxApi.Models.Folder", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("folerId");

                    b.Property<string>("name");

                    b.Property<long>("organizationId");

                    b.HasKey("id");

                    b.ToTable("folders");
                });

            modelBuilder.Entity("DroppboxApi.Models.Organization", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("DroppboxApi.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DroppboxApi.Models.User_Organisation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("organisationId");

                    b.Property<long>("userId");

                    b.HasKey("id");

                    b.ToTable("user_organisation");
                });
#pragma warning restore 612, 618
        }
    }
}
